#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
A daemon which monitors one or more groups of Process Variables
and sends email periodic email with a list alarms which occur.
"""

import logging
LOG = logging.getLogger(__name__)

if __name__=='__main__':
    from alarmmail.main import main
    try:
        main()
    except (SystemExit, KeyboardInterrupt):
        raise
    except:
        LOG.exception("Unhandled exception")
        raise
    else:
        LOG.info('Done')
